sublet_project/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  root 'posts#index', as: 'home'
  post 'posts/:id/comments' => 'posts#add_comment'

end

sublet_project/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, :description, presence: true
  belongs_to :post
end

sublet_project/app/models/post.rb
class Post < ActiveRecord::Base
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :picture, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  has_attached_file :picture, :default_url => "/empty.png"

  validates :title, :description, :address, :price, :startdate, :enddate, :owner, :phone, presence: true
  has_many :comments
end

sublet_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sublet_project/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @comment.author = params[:author]
    @comment.description = params[:description]
    @comment.post_id = params[:post_id]
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        # format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :author)
    end
end

sublet_project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /posts/1/comments
  def add_comment
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:picture, :title, :description, :address, :price, :startdate, :enddate, :owner, :phone)
    end
end

sublet_project/app/helpers/application_helper.rb
module ApplicationHelper
end

sublet_project/app/helpers/comment_helper.rb
module CommentHelper
end

sublet_project/app/helpers/comments_helper.rb
module CommentsHelper
end

sublet_project/app/helpers/posts_helper.rb
module PostsHelper
end

sublet_project/app/views/comments/_form.html.erb
<%= form_tag(post_comments_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :Name %><br>
    <%= text_field_tag "author"%>
  </div>
  <div class="field">
    <%= label_tag :Comment %><br>
    <%= text_field_tag "description" %>
  </div>
  <div class="actions">
    <%= submit_tag 'Post Comment', ({:class => "btn btn-primary"}) %>
  </div>
<% end %>

sublet_project/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

sublet_project/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.author %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

sublet_project/app/views/comments/new.html.erb
<div class="container">
  <h1>New Comment</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

sublet_project/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

sublet_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubletProject</title>
  <%= stylesheet_link_tag    'welcome' %>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="#">Find My Sublet</a>
         </div>
         <div id="navbar" class="collapse navbar-collapse">
           <ul class="nav navbar-nav">
             <li><%= link_to "Home", home_path %></li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "Create Sublet", new_post_path %></li>
           </ul>
         </div><!--/.nav-collapse -->
       </div>
     </nav>
<%= yield %>

<div class="container">
</body>
</html>

sublet_project/app/views/posts/_form.html.erb
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :startdate %><br>
      <%= f.text_field :startdate, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :enddate %><br>
      <%= f.text_field :enddate, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :owner %><br>
      <%= f.text_field :owner, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone, {:class => 'form-control'} %>
    </div>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.file_field :picture %>
    </div>
    <div class="actions">
      <%= f.submit({:class => "btn btn-primary"}) %>
    </div>
<% end %>

sublet_project/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

sublet_project/app/views/posts/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <% @posts.each do |post| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <%=image_tag post.picture.url(:square) %>
            <div class="caption">
              <h3><%= post.title %></h3>
              <p> <%= post.description %> </p>
              <p> <%= post.address %> </p>
              <p> <%= "$#{post.price}"%> </p>
              <p> <%= "#{post.startdate} ~ #{post.enddate}" %> </p>
              <%= link_to 'Details', post, :class => 'btn btn-default' %>
            </div>
          </div>
        </div>
    <%end%>
  </div>
</div>

sublet_project/app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

sublet_project/app/views/posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="well">
    <div class="post_image">
      <%= image_tag @post.picture.url(:medium) %>
    </div>
  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @post.description %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @post.address %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @post.price %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= "#{@post.startdate} ~ #{@post.enddate}" %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @post.owner %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @post.phone %>
  </p>

  <%= link_to 'Back', posts_path %>
  </div>
  <br>
  <h2> Comments </h2>
  <% if @post.comments.empty? %>
    <div class="container">
      <h5> Be the first to add a comment! </h5>
    </div>
  <% else %>
    <% @post.comments.each do |comment| %>
      <h5><%="#{comment.author}: #{comment.description}"%></h5>
    <% end %>
  <% end %>
  <!--- new comment path -->
  <a class="comment_btn btn btn-success" href="/posts/<%= @post.id %>/comments/new"> Add comment </a>
</div>